#!/usr/bin/env python3 
import csv
import os 
import sys
import pandas as pd
import mysql.connector
import glob
from sqlalchemy import create_engine
os.chdir(os.path.dirname(sys.argv[0]))
dbPostfixes=['a','b']
with open('currentDBIndex') as x: currentDBIndex = x.read()
currentDBIndex=1-int(currentDBIndex)
x.close()
print(currentDBIndex)
with open('db_%s_private.csv' %(dbPostfixes[currentDBIndex]), newline='') as csvfile:
	reader = csv.DictReader(csvfile)
	for row in reader:	
		engine = create_engine('mysql+mysqlconnector://%s:%s@%s/%s' %(row['user'],row['password'],row['host'],row['db']), echo=False)
filesWithNulls=['CASE_ENFORCEMENTS']
largeTables=['ECHO_EXPORTER','NPDES_EFF_VIOLATIONS','FRS_PROGRAM_LINKS','NPDES_INSPECTIONS','NPDES_QNCR_HISTORY','SDWA_VIOLATIONS','SDWA_PUB_WATER_SYSTEMS','SDWA_ENFORCEMENTS']
with open('files.csv', newline='') as csvfile:
	reader = csv.DictReader(csvfile)
	uniqueZips=[]
	tables=[]
	for row in reader:
		tables.append(row['CSV FILE'])
		if row['Location'] not in uniqueZips:
			uniqueZips.append(row['Location'])
	for location in uniqueZips:
		if not os.path.isfile('zips/%s' %(location)):
			print("Getting %s" %(location))
			os.system("./wgetEPA %s" %(location))
			os.system("./unzipEPA %s" %(location))
		else:
			print("File %s  already exists" %(location))
			os.system("./unzipEPA %s" %(location))
			os.remove('./zips/%s.csv' %(location))
	exit
	for nulledFile in filesWithNulls:	
		os.system("./stripNulls %s" %(nulledFile))
	for table in tables:
		if table not in largeTables:
			print(table)
			engine.execute("truncate `%s`" %(table))
			df=pd.read_csv('./CSV/%s.csv' %(table),low_memory=False)
			df.to_sql(table,engine,if_exists='append',index=False)	
			#os.system("./csvsqlEPA %s" %(table))
			os.remove('./CSV/%s.csv' %(table))
	for table in largeTables:
		if table in tables:
			print (table)
			engine.execute("truncate `%s`" %(table))
			os.system("./chunkFile %s" %(table))
			chunks=glob.glob('./CSV/%s_[0-9]*.csv' %(table)) 
			for path in chunks:
		
				fileStem=path.split("/")[2].split(".")[0]
				df=pd.read_csv('./CSV/%s.csv' %(fileStem))
				df.to_sql(table,engine,if_exists='append', index=False)	
				os.remove('./CSV/%s.csv' %(fileStem))
			os.remove('./CSV/%s.csv' %(table))
			#os.system("./csvsqlEPA %s %s" %(fileStem,table))
		#os.system("./csvsqlLargeEPA %s" %(table))
with open('currentDBIndex', 'w') as writer: 
	writer.write(currentDBIndex)

